### ISSUE TITLE
change name of package 'code'

### ISSUE THREAD

**Issue by ascourtas** [NUCS349/hw1-decision-trees#18]
PyCharm is a highly popular Python IDE, recommended for a number of Python-related courses. Since there's a package named `code` in this repo, PyCharm cannot run any code in its console (issue described [here](https://stackoverflow.com/questions/29172399/unable-to-debug-in-pycharm-because-of-an-importerror-in-pydevconsole-py/35762634)). This prevents efficient debugging of this project, leaving students to pursue less effective ways of debugging, or to create hacky workarounds. Until Pycharm fixes this bug (which seems unlikely, as it's been present since at least 2015), it would be hugely helpful if the `code` package could be renamed to something else (e.g. `app`, `program`, `decision_tree`, etc.) to allow students to debug within PyCharm.

**Comment by fschiffers** [comment]
We've changed this now for HW1
