### ISSUE TITLE
Test experiment uses platform-specific directory string

### ISSUE THREAD

**Issue by maxrmorrison** [NUCS349/hw1-decision-trees#5]
The `accuracies` dictionary is populated with os-specific file paths. The assertion statement uses a file path format not compatible with, e.g., Windows. The dictionary key used should probably be a member of the `datasets` list.

**Comment by pseeth** [comment]
Damn you and your windows. Will fix! Thanks.

**Comment by maxrmorrison** [comment]
Closed by 68c0ecc1ca31af7d7e4165ecde08e5bf409d9407
